# Simple Voice Chat server configuration
port=31878
bind_address=*
max_voice_distance=48
whisper_distance=24
codec=VOIP
mtu_size=1275
tcp_rate_limit=16
keep_alive=1000
enable_groups=true
voice_host=31878
allow_recording=false
spectator_interaction=false
spectator_player_possession=false
force_voice_chat=false
login_timeout=10000
broadcast_range=-1.0
allow_pings=true
use_natives=true
threaded_server_support=false
